#[[headers]]
#  for = "/*"
#  [headers.values]
#    Cross-Origin-Opener-Policy = "same-origin"
#    Cross-Origin-Embedder-Policy = "require-corp"

#[[headers]]
#  for = "/*"
#  [headers.values]
#    Cross-Origin-Opener-Policy = "same-origin"
#    Cross-Origin-Embedder-Policy = "require-corp"
#    Cross-Origin-Resource-Policy = "cross-origin"
#    Access-Control-Allow-Origin = "*"

[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
